<?php
namespace App\Controller;
use App\Form\TicketsType;
use App\Repository\TicketsRepository;
use App\Entity\Project2;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Repository\UserRepository;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use App\Entity\Comments;
use App\Entity\Tags;
use App\Repository\TagsRepository;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use App\Entity\User;
use App\Entity\TicketsTags;
use App\Entity\Tickets;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
/**
 * @Route("/tickets")
 */
class TicketsController extends AbstractController
{
    /**
     * @Route("/", name="tickets_index", methods="GET")
     */
    public function index(TicketsRepository $ticketsRepository): Response
    {
        return $this->render('tickets/index.html.twig', ['tickets' => $ticketsRepository->findAll()]);
    }
    /**
     * @Route("/new/{id}", name="tickets_new", methods="GET|POST")
     */
    public function new(Request $request, Project2 $project): Response
    {
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');
        $user = $this->getUser();
        $ticket = new Tickets();
        $ticket->setcreaterId($user->getId());
        $ticket->setprojectId($project->getId());
        $repository = $this->getDoctrine()->getRepository(User::class);
        $user = $this->getDoctrine()
          ->getRepository(User::class)
          ->findBySomeField();
           $username = array();
           foreach ($user as $row)
          {
            $username[$row['username']] = $row['id'];
          }
        $form = $this->createFormBuilder($ticket)
            ->add('name', TextType::class)
            ->add('description', TextType::class)
            ->add('type', ChoiceType::class, array(
                  'choices'  => array(
                  'task' => 1,
                  'bug' => 2,
                  ),
                  ))
           ->add('status', ChoiceType::class, array(
                  'choices'  => array(
                  'new' => 1,
                  'in progress' => 2,
                  'end' => 3,
                  ),
                  ))
          ->add('assignedId', ChoiceType::class, array(
                  'choices'  => $username,
                   ))
          ->add('projectId', HiddenType::class)
          ->add('createrId', HiddenType::class)
          ->add('brochure', FileType::class, array('label' => 'Brochure (file)'))
          ->add('save', SubmitType::class, array('label' => 'Create ticket'))
          ->getForm();
              $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()) {
                 $file = $ticket->getBrochure();
                 $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();
                 try {
                 $file->move(
                    $this->getParameter('brochures_directory'),
                    $fileName
                 );
                 } catch (FileException $e) {
                 // ... handle exception if something happens during file upload
                 }

                 // updates the 'brochure' property to store the PDF file name
                 // instead of its contents
                 $ticket->setBrochure($fileName);

              // ... persist the $product variable or any other work
          //return $this->redirect($this->generateUrl('app_product_list'));
  //}
                 $ticket = $form->getData();
                 $entityManager = $this->getDoctrine()->getManager();
                 $entityManager->persist($ticket);
                 $entityManager->flush();
            return $this->redirectToRoute('project2_show',array('id'=>$project->getId()));
            }
            return $this->render('tickets/new.html.twig',
            array('ticket' => $ticket,
            'form' => $form->createView(),
             ));
    }
    private function generateUniqueFileName()
{
// md5() reduces the similarity of the file names generated by
// uniqid(), which is based on timestamps
return md5(uniqid());
}
    /**
     * @Route("/{id}", name="tickets_show", methods="GET")
     */
    public function show(Tickets $ticket): Response
    {
      $manager = $this->getDoctrine()->getManager();
      $manager->persist($ticket);
      $manager->flush();
      $repository = $this->getDoctrine()->getRepository(Comments::class);
      $comments = $repository->findBy(['ticket_id' => $ticket->getId(),]);
      return $this->render('tickets/show.html.twig', ['ticket' => $ticket, 'comments' => $comments ]);
    }
    /**
     * @Route("/{id}/edit", name="tickets_edit", methods="GET|POST")
     */
    public function edit(Request $request, Tickets $ticket, AuthorizationCheckerInterface $authChecker): Response
    {
     // check for "edit" access: calls all voters
        $this->denyAccessUnlessGranted('edit', $ticket);
        $user = $this->getDoctrine()
         ->getRepository(User::class)
         ->findBySomeField();
          $username = array();
        $tags = $this->getDoctrine()
         ->getRepository(Tags::class)
         ->findBySomeField($ticket->getId());
         $tagsName = array();
           foreach ($tags as $key) {
                   $tagsName[] = $key['name'];
             // code...
           }
         $tagsNameImpl = implode(",", $tagsName);
          foreach ($user as $row)
                 {
                   $username[$row['username']] = $row['id'];
                 }
        $form = $this->createFormBuilder($ticket)
            ->add('name', TextType::class)
            ->add('description', TextType::class)
            ->add('type', ChoiceType::class, array(
                  'choices'  => array(
                  'task' => 1,
                  'bug' => 2,
                  ),
                  ))
           ->add('status', ChoiceType::class, array(
                  'choices'  => array(
                  'new' => 1,
                  'in progress' => 2,
                  'end' => 3,
                  ),
                  ))
          ->add('assignedId', ChoiceType::class, array(
                  'choices'  => $username,
                   ))
            ->add('projectId', HiddenType::class)
            ->add('createrId', HiddenType::class)
            ->add('tags', TextType::class,array(
               "mapped" => false, 'data' => "$tagsNameImpl"))
            ->add('save', SubmitType::class, array('label' => 'Create ticket'))
            ->getForm();
              $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()) {
                    $ticket = $form->getData();
                    $tags = $form->get('tags')->getData();
                    // переводим строку в массив
                    $tags = explode(",", $tags);
                    //удалим ненужные связи
                    $tagDel = array_diff($tagsName, $tags);
                    if($tagDel){
                            foreach($tagDel as $key){
                                    $repository = $this->getDoctrine()->getRepository(Tags::class);
                                    $tag = $repository->findOneBy(['name' => $key,]);
                                    $manager = $this->getDoctrine()->getManager();
                                    $manager->remove($tag);
                                    $manager->flush();
                            }
                    }
                    $UniqTag = array_diff($tags, $tagsName);
                    // проверим, являются ли уникальные теги в тикете уникальными в таблице tegs
                    $UniqTagInTable = array();
                    $repository = $this->getDoctrine()->getRepository(Tags::class);
                            foreach($UniqTag as $key){
                              echo $key;
                            $Tegs = $repository->findBy(['name' => $key,]);
                          if (!$Tegs){
                            $tag = new Tags();
                            $tag ->setName($key);
                            $manager = $this->getDoctrine()->getManager();
                            $manager->persist($tag);
                            $manager->flush();
                            //делаем связи между тегами и тикет тегами
                            $ticketTag = new TicketsTags();
                            $ticketTag ->setTicketId($ticket->getId());
                                //находим id нужного тега
                                $repository = $this->getDoctrine()->getRepository(Tags::class);
                                $tags = $repository->findOneBy(['name' => $key,]);
                                //
                            $ticketTag ->setTagId($tags->getId());
                            $manager->persist($ticketTag);
                            $manager->flush();
                                    }
                                    else{
                                      //делаем связи между тегами и тикет тегами
                                              $ticketTag = new TicketsTags();
                                              $ticketTag ->setTicketId($ticket->getId());
                                                  //находим id нужного тега
                                              $repository = $this->getDoctrine()->getRepository(Tags::class);
                                              $tags = $repository->findOneBy(['name' => $key,]);
                                                  //
                                              $ticketTag ->setTagId($tags->getId());
                                              $manager = $this ->getDoctrine() ->getManager();
                                              $manager->persist($ticketTag);
                                              $manager->flush();
                                      }
                          }
                return $this->redirectToRoute('tickets_show',array('id' => $ticket ->getId()));
              }
            return $this->render('tickets/new.html.twig',
            array('ticket' => $ticket,
            'form' => $form->createView(),
             ));
    }
    /**
     * @Route("/{id}", name="tickets_delete", methods="DELETE")
     */
    public function delete(Request $request, Tickets $ticket): Response
    {
        $this->denyAccessUnlessGranted('edit', $ticket);
        if ($this->isCsrfTokenValid('delete'.$ticket->getId(), $request->request->get('_token'))) {
            $manager = $this->getDoctrine()->getManager();
            $manager->remove($ticket);
            $manager->flush();
        }
        return $this->redirectToRoute('tickets_index');
    }
}
